### ISSUE TITLE
Add check option to backend

### ISSUE THREAD

**Issue by bpbp-boop** [evrardjp/ansible-haproxy#5]
Hi, thanks for the great playbook!

It would be useful to have an extra check option in the backend options. I am currently doing this

```
        backends:
          - name: cluster_backend_writes
            servers:
              - name: 'server-one'
                ip: '192.168.10.206:3306 check'
            backups:
              - name: 'server-one'
                ip: '192.168.10.207:3306 check'
              - name: 'server-one'
                ip: '192.168.10.208:3306 check'
```

Ideally it would be good to have check as its own option:

```
        backends:
          - name: cluster_backend_writes
            servers:
              - name: 'server-one'
                ip: '192.168.10.206:3306'
                check: true
etc...
```
